env:
    CIRRUS_SHELL: bash

task:
  name: "ROM Build"
  timeout_in: 180m
  container:
      image: ghcr.io/sushrut1101/docker:latest
      cpu: 8
      memory: 20G

  Setup:
    - curl -sL https://raw.githubusercontent.com/shashankx86/temp/main/srcipts/Setup.sh | bash

  Sync:
    - curl -sL https://raw.githubusercontent.com/shashankx86/temp/main/srcipts/Sync.sh | bash

  Build:
    - curl -sL https://raw.githubusercontent.com/shashankx86/temp/main/srcipts/Build.sh | bash

  Upload:
    - curl -sL https://raw.githubusercontent.com/shashankx86/temp/main/srcipts/Uplaod.sh | bash
