name: SSH (L-1)

on:
  workflow_dispatch:

jobs:
  setup-ssh:
    name: Setup SSH
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
