name: SSH (win-1)

on:
  workflow_dispatch:

jobs:
  setup-ssh:
    name: Setup SSH Action
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH Action
      uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
