name: SSH-Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Modem SDK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build Modem SDK
      run: |
        git clone https://github.com/the-modem-distro/pinephone_modem_sdk -b mickledore
        cd pinephone_modem_sdk
        make everything VERSION="0.0.1"

  setup-ssh:
    name: Setup SSH
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
