name: SSH-Build

on:
  workflow_dispatch:

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
    - name: Install Required Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint xterm python3-subunit mesa-common-dev zstd liblz4-tool gcc-arm-none-eabi

  build:
    name: Build Modem SDK
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build Modem SDK
      run: |
        git clone https://github.com/the-modem-distro/pinephone_modem_sdk -b mickledore
        cd pinephone_modem_sdk
        make everything VERSION="0.0.1"

  setup-ssh:
    name: Setup SSH
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
